version: '3.4'

services:
  # databases
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # this info is from docker hub
  
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"     
  
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb # make sure db image is deployed b4 this one
    ports:
      - "8000:80" # Expose to 8000 localhost  

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8001:80"